language: python

python:
  - "3.8"

before_script:
  - python manage.py migrate

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test polls

after_success:
  - coveralls
